
    # x0 = Bus()
    # x1 = Bus()
    # x2 = Bus()
    # x3 = Bus()
    # x4 = Bus()
    # x5 = Bus()
    # x6 = Bus()
    # x7 = Bus()
    # x8 = Bus()
    # x9 = Bus()
    # n1 = NotGate()
    # a1 = AND_GATE()
    # a2 = AND_GATE()
    # o = OrGate()
    # dl1 = Circuit.retrieve("./BuiltCircuits/DLatchClocked.json")

    # n1.appendInput(x1)
    # n1.appendOutput(x3)
    # a2.appendInput(x0)
    # a2.appendInput(x1)
    # a2.appendOutput(x5)
    # a1.appendInput(x3)
    # a1.appendOutput(x4)
    # o.appendInput(x5)
    # o.appendOutput(x6)
    # o.appendInput(x4)
    # dl1.appendInput(x6)
    # dl1.appendInput(x2)
    # dl1.appendOutput(x7)
    # a1.appendInput(x7)

    # x0.recieveLeft(1)
    # x1.recieveLeft(1)
    # x2.recieveLeft(0)

    # n1.process()
    # a1.process()
    # a2.process()
    # o.process()
    # dl1.process()

    # print(x7.leftNode)